### ISSUE TITLE
Unraid error 404 nginx 

### ISSUE THREAD

**Issue by naddel91** [dkaser/unraid-tailscale#109]
### Description

Hi at all,

I get the 404 nginx error on my fresh install of unraid. What am I missing? Shouldn't this work out of the box? I cannot even login in tailscale because the WebUI is missing.

Please give me a hint.

Steps to reproduce
https://forums.unraid.net/topic/164192-tailscale-plugin-not-working/

### Plugin Version

newest

### Unraid Version

newest

**Comment by dkaser** [comment]
You need to provide a copy of the plugin diagnostics.

**Comment by naddel91** [comment]
will do, just give me a hint how to get those diagnostics, please.

**Comment by naddel91** [comment]
> You need to provide a copy of the plugin diagnostics.

Same problem here. Diagnostics attached:

https://www.reddit.com/r/unRAID/comments/1bw3q1d/tailscale_404_error_in_the_plugin/?sort=new

**Comment by Nitromatt** [comment]
[Tower-tailscale-diag-20240525-104403.zip](https://github.com/dkaser/unraid-tailscale/files/15440971/Tower-tailscale-diag-20240525-104403.zip)

Have experienced the same issue with a new install this morning.

Receiving an error when on the Tailscale tab under settings

404 Not Found
nginx
