### ISSUE TITLE
[Bug]: notices about tailscale state being backed up

### ISSUE THREAD

**Issue by Dragonz423** [dkaser/unraid-tailscale#111]
### Description

Hi, I’m using the tailscale plugin and not the flash drive backup through management access. I got this ping for the first time and now a few of my servers are reporting it. I do also use app data backup and restore which has the flash drive backup option on so I’m betting that’s it. Just wanting advice and suggestions about the best way to fix this. 

### Plugin Version

2024.08.28

### Unraid Version

6.12.11

**Comment by dkaser** [comment]
Can you generate diagnostics from inside the Tailscale plugin and post them?

I just tried configuring the app data backup on one of my test servers, and it doesn't create the files that would cause that alert to trigger.

**Comment by Dragonz423** [comment]
[GigaServer-tailscale-diag-20240831-103059.zip](https://github.com/user-attachments/files/16825169/GigaServer-tailscale-diag-20240831-103059.zip)
Here you go.

**Comment by dkaser** [comment]
It looks like the Unraid Connect flash backup is enabled on your server:

```
Jul 23 19:37:26 GigaServer flash_backup: flush: /usr/local/emhttp/plugins/dynamix.my.servers/scripts/UpdateFlashBackup update
...
Aug 14 01:00:39 GigaServer flash_backup: flush: /usr/local/emhttp/plugins/dynamix.my.servers/scripts/UpdateFlashBackup update
```

This means that the feature is behaving as intended. You should follow the steps to remove and recreate the flash backup.

**Comment by Dragonz423** [comment]
Hmm that’s odd because I’ve been signed out of unraid connect for so long. I’ll take a look tomorrow and see if that resolves it. Thanks! 
![IMG_5351](https://github.com/user-attachments/assets/81dfc6d8-496e-4b96-9db7-325aa2e9ec2c)

**Comment by Dragonz423** [comment]
Went ahead and signed in and deactivated then deleted. For now I did reactivate to see if it’ll send the ping again. Is there a timeframe to know if it will? I’m fine with leaving it off overall as I don’t need the backup through unraid connect.

**Comment by dkaser** [comment]
That's interesting... I'll pass that on to the Unraid folks in case it's something they want to  fix in Connect. 

The backup check runs on each install/update of the plugin, so it can be triggered either by waiting for the next update, or by restarting your server.

**Comment by ljm42** [comment]
Interesting, your system was in a strange half-signed in state that allowed flash backup to run in the background. You disabled it correctly - sign in, disable and delete:
  https://docs.unraid.net/connect/flash-backup/#disabling-flash-backup

> For now I did reactivate to see if it’ll send the ping again. Is there a timeframe to know if it will? 

I am confident it will not, the Tailscale plugin has been updated to block the sensitive files from being backed up.

> I’ve been signed out of unraid connect for so long

Note that if you are not going to sign in to Unraid Connect you should just uninstall the plugin. It doesn't really provide any benefits unless you sign in.
