### ISSUE TITLE
6.12-RC5: NGINX FLOODING /VAR/LOG WITH NCHAN: OUT OF SHARED MEMORY

### ISSUE THREAD

**Issue by russkinz** [dkaser/unraid-tailscale#36]
Hello

Noticed that the above was happening after upgrading to 6.12-RC5 - the issues stopped entirely after I moved Tailscale to my pfSense router (which realistically is where it should have been anyway!).

Thought I'd let you know. Have attached an Unraid diagnostics report from around the time I first noticed the issue.

[babel-diagnostics-20230506-1546.zip](https://github.com/dkaser/unraid-tailscale/files/11468975/babel-diagnostics-20230506-1546.zip)

No idea how NGINX/etc relates to this plugin, and am happy to reinstall the plugin and generate more logs if you need.

**Comment by dkaser** [comment]
Thanks for the report. nginx is what runs the Unraid web UI/API.

This seems to be a common issue, I found the following thread on the Unraid forums: https://forums.unraid.net/topic/86114-nginx-running-out-of-shared-memory/

From that thread, I noticed the following comment. Is there any chance that this could have applied?

> Make sure you don't have an Android device with a browser opened to the GUI, it's known to cause issues when the device is sleeping.

**Comment by russkinz** [comment]
Thought I'd give you an update on this - after a lot of digging and forum archeology, it looks (to me) like this is a known NGINX bug in Unraid. It's been around since 6.9, and seems to occur when a browser window is left open on the Unraid homepage then the device disconnects from the network / goes to sleep. I've reported to Unraid but so have many others. Hopefully it'll be fixed in 6.12 final, or 6.13 - it seems like they're updating some of the out-of-date modules (like Docker) with this build.

The unfortunate knock-on effect is that it also takes out the NGINX process and Docker network if it happens too often, requiring a hard reset of the device (NGINX hangs and can't be stopped even via pkill in the console). Also unfortunate is that from my testing/experience, no matter where you connect to Tailscale from (either on the Unraid server or via another device - i.e. via a pfSense router), it occurs a LOT more often - presumably because the device I/you are connecting from is more transient than others.

Anyway - closing. Thank you for your awesome work, looking forward to the new build for 6.12 whenever it's ready :)
