### ISSUE TITLE
New Feature: --advertised-routes interface

### ISSUE THREAD

**Issue by dkaser** [dkaser/unraid-tailscale#65]
- Validate input
- Set on start similar to accept-routes and accept-dns

**Comment by dkaser** [comment]
This was added to the upstream web interface.

**Comment by geoah** [comment]
Hey there, I'm trying to figure out if there is a way to set (outgoing) advertised routes using this plugin.
The ui at least of the latest version (2024.01.24b) doesn't seem to have an options for this but this ticket mentions it was added, even in the "advanced" mode of the ui. Am I missing something?

Thank you for taking the time to make this, it's really appreciated.

**Comment by dkaser** [comment]
@geoah You will need to switch into "editing" mode on the first page of the plugin settings (the "Tailscale" tab, not the "Settings" tab). Click "Viewing", then log in, and you will be able to update subnet routes.
