### ISSUE TITLE
supporting new Tailscale web client

### ISSUE THREAD

**Issue by willnorris** [dkaser/unraid-tailscale#86]
Hey @dkaser, thanks for your work on this. I'm an engineer at Tailscale that is working on the web client used by this plugin.  As I'm sure you're aware, it hasn't gotten much love in quite a long time, but we're now actively working on bringing it up to par with the other clients.

I'm not an unraid user myself, but I've got a test instance setup and your plugin installed.  I'm curious if there is some easy way that I'm missing to test out unreleased version of the Tailscale client.  I gather that I could simply change the tailscale package URL in `tailscale.plg`, but for some reason I can't figure out how to load that plugin file into unraid.  On Synology and QNAP, there's just a "manual install" button, but I'm not seeing anything like that for unraid.  Do you have steps that you follow to test things out before publishing a release?

**Comment by willnorris** [comment]
After getting a better understanding how unraid works, I've got this working well enough.  The new web client definitely breaks in this plugin because of how it now loads multiple web resources.  Whereas before it was just a single HTML page with a little embedded JS and CSS, and we never really cared about the path of the request URL.  We've now split out CSS and JS assets, as well as have a small API to serve the frontend, and so all of those need to be routed appropriately.

I got this working for unraid-tailscale, but it required changes both to the unraid nginx config and unraid-tailscale-utils.

## Changes to unraid nginx config
We need to be able to send requests of the form `/plugins/tailscale/interface.php/assets/index.js`.  This is pretty easily doable by changing `/etc/nginx/conf.d/locations.conf` from:

``` nginx
location ~ \.php$ {
    include fastcgi_params;
}
```

to this instead:

``` nginx
location ~ ^(.+\.php)(.*)$ {
    fastcgi_split_path_info  ^(.+\.php)(.*)$;
    include fastcgi_params;
}
```

The challenge there is that this file is overwritten by `/etc/rc.d/rc.nginx` every time it starts up.  So I'm not sure how open unraid would be to making this change upstream, or if there is a semi-supported way for plugins to make these kinds of customizations?

## unraid-tailscale-utils

The change in `unraid-tailscale-utils` is pretty minor, and I can send a pull request over.  Basically, instead of throwing away the response headers from the tailscale cgi process we need to pass them along.  `interface.php` would basically end with:

``` php
$out = explode(PHP_EOL, $output);
$headers = true;
foreach ($out as $line) {
    if ($headers) {
        if (trim($line) == "") {
            $headers = false;
            continue;
        }
        header($line);
    } else {
        echo($line . PHP_EOL);
    }
}
```

There are also a couple of small changes I need to make in the new Tailscale web client itself, but that's simple enough.

I'd love to hear your thoughts, and if you have other ideas of how to address this.  You can test out the new web client in the latest unstable build at https://pkgs.tailscale.com/unstable/ (though I still need to make those changes to work with unraid).

**Comment by dkaser** [comment]
Hey there! Thanks for the info on this.

I'm glad you got the testing working (I usually just replace the files in `/usr/local/emhttp/plugins/tailscale/bin` for initial testing, that gets wiped out on reboot but it's good enough until I'm ready to test the package itself).

Any needed changes to `interface.php` will be fine with me... after all, its only reason for existence is to wrap the CGI calls to tailscale :)

For the nginx configuration -- in general, I'm hesitant to live-patch any built-in config files, since that nginx instance runs the Unraid WebGUI and all other plugins. I can propose the change upstream... I don't think that change would break other things, but I also don't want to patch it during the plugin install and accidentally become the plugin that doesn't play nicely with others :(

An alternative solution might be to add a second location block to `locations.conf` to more specifically match `/plugins/tailscale/interface.php`, then add any customizations there (leaving the original block intact). That would let the CGI wrapper get what it needs without changing the behavior for anything else.

**Comment by willnorris** [comment]
correction... I'm going to have the platforms pass the URL prefix to the web CLI.  See https://github.com/tailscale/tailscale/pull/9189.  So `interface` would change to use the command:

```
$cmd            = "tailscale --socket=/var/run/tailscale/tailscaled.sock web -cgi -prefix=/plugins/tailscale/interface.php/";
```

**Comment by willnorris** [comment]
yeah, that's basically what I ended up doing during testing... just scp'ing the binary into place.

And I completely agree about not wanting to mess with the main nginx config. It was a total hack to get it working, but it did confirm that it works.  Adding an additional location block is certainly cleaner, but you still run into the same problem of `/etc/rc.d/rc.nginx` overwriting the entire `locations.conf` file on restart.  So I'm not sure what the cleanest approach the unraid folks would be comfortable with.  Maybe have `/etc/nginx/conf.d/servers.conf` end with something like:

``` nginx
server {
    ...
    include /etc/nginx/conf.d/locations.conf;
    include /etc/nginx/conf.d/locations.*.conf;
}

So then you could drop in a `/etc/nginx/conf.d/locations.tailscale.conf` file or something?

**Comment by dkaser** [comment]
It's not just `locations.conf ` that gets overwritten -- `/etc` isn't persistent across reboots (Unraid runs from memory and essentially reinstalls itself -- and all the plugins -- on every boot).

If we have a location block (scoped to this plugin) to add to `locations.conf`, I can just have the installation script in the .plg file `>>` that into `/etc/nginx/conf.d/locations.conf` then restart nginx, that'll let the changes persist.

**Comment by willnorris** [comment]
ah, got it.  I was just noting that if you run `/etc/rc.d/rc.nginx restart` or `reload` (which is what I was doing while I was testing changes), then it overwrites any changes in `locations.conf`.  So even if you append a location block, I think it'll get overwritten when nginx starts up, won't it?  And if you add it after nginx starts, then it won't take effect.

**Comment by dkaser** [comment]
Digging a little more... it looks like /etc/rc.d/rc.nginx rebuilds both servers.conf and locations.conf on every service restart.

I sent a note to the Unraid folks to see if I could get something like `include /etc/nginx/conf.d/locations.conf.d/*.conf;` added to the end of locations.conf.

**Comment by dkaser** [comment]
I'm working with the Unraid folks on a PR to put the config settings in by default... trying to test, though, I discovered that the latest unstable build (1.49.195) gives me this message:

> Tailscale was built without the web client. See [Building the web client](https://github.com/tailscale/tailscale#building-the-web-client) for more information.

I'm also trying to build from source following the instructions in the repo, but that's proving to be a bit difficult as well.

**Comment by willnorris** [comment]
oops... I'll double check our builders to make sure they're doing the right thing. (It certainly looks like they aren't!)

**Comment by dkaser** [comment]
No worries. You might also want to add that you need to run `./tool/yarn --cwd client/web` (before running the build command) to the README file :)

**Comment by dkaser** [comment]
It turns out that it was a problem with how I defined the nginx configuration on my test instance... the script wasn't loading when I accessed the page, the error message just had me chasing the wrong problem.

I just sent a PR (unraid/webgui#1421) for Unraid to include the needed change in the base system (from conversation, that seems easier than trying to incorporate it in the plugin install).
