### ISSUE TITLE
Can’t connect to unraid webui remotely 

### ISSUE THREAD

**Issue by guycobb2** [dkaser/unraid-tailscale#87]
Can no longer connect to unraid webui remotely. Recently setup funnel, so I could certainly have messed up something. Can still connect to all the containers just fine and the funnel works as expected….just can’t connect to the webui.

**Comment by dkaser** [comment]
It looks like your funnel is running on port 443, and so is the webgui, so Tailscale and nginx are probably fighting over the port.

Try changing your HTTPS port in Settings -> Management Access, then access the webgui on that port instead.

**Comment by guycobb2** [comment]
You are 100% right and that makes perfect sense. I knew I’d done something. 🤣 appreciate it. If that doesn’t work for some reason I’ll report back. But I’m sure that’s it. I’ll have to look and see what the other port options were. I seem to recall on three available to use.

**Comment by guycobb2** [comment]
as best i can tell i changed the port to 10000.  i can connect to the container i was when off the tailnet, so i believe the change took hold and all is well.  i'm still not able to connect to the webui when i have my phone on the tailnet.  if you get a minute, see what else i may have screwed up.
[BitLord-tailscale-diag-20230908-173151.zip](https://github.com/dkaser/unraid-tailscale/files/12564025/BitLord-tailscale-diag-20230908-173151.zip)

**Comment by guycobb2** [comment]
Just a follow up. Tailscale was still bound to port 443. I deleted plug-in and re-setup everything to a different port. All seems to be working as expected now.

**Comment by guycobb2** [comment]
Just a follow up. Tailscale was still bound to port 443. I deleted plug-in and re-setup everything to a different port. All seems to be working as expected now.
